### PR TITLE
Fix: iOS background worker

### PR DESCRIPTION
**Pull request by armandsLa**
There is an issue with how `HomeWidgetBackgroundWorker` uses `async/await` in its iOS implementation. Currently, the `run` method returns immediately, before the platform channel can be initialized and the Flutter callback performed.

I've refactored the `HomeWidgetBackgroundWorker` with a proper `async/await` implementation. Now, the `run` method will return only after the interactivity callback in Flutter has been executed.

### CODE REVIEW

**Comment by armandsLa** [comment]
Unfortunately, the issue still persists. I will do more testing and improve this PR

**Comment by armandsLa** [comment]
I've made the `url` input parameter of the `sendEvent` method required because it is required in Flutter and would throw an exception if not present.

**Comment by armandsLa** [comment]
I've been testing this PR over the weekend and can confirm that it resolves the issue where widgets might not reload with new data after `saveWidgetData` and `updateWidget` are called from the interactivity callback. This issue only occurred when the interactivity callback took a bit longer to execute.

To better understand the issue, the sequence of actions was as follows:
1. Call `HomeWidgetBackgroundWorker.run` from an iOS widget.
2. Receive the interactivity callback in Flutter.
3. Execute a task that takes longer to complete.
4. Call `saveWidgetData` with the new data.
5. Immediately call `updateWidget` thereafter.

In this scenario, the widget would reload, but with the previously saved data, not the one saved in step 4. I still have no idea why this is happening. My best guess is that returning `.result()` from an `Intent` before data gets saved halts the internal synchronization of user defaults.

**Comment by armandsLa** [comment]
@Oleksandr32 Thank you for reporting this issue. I was calling `HomeWidgetBackgroundWorker` from the main thread, so I never encountered this error. I have now added `Dispatch` to ensure it is safe to call `HomeWidgetBackgroundWorker` from any thread. Please let me know if this resolves the issue.

**Comment by Oleksandr32** [comment]
@armandsLa  The issue has been resolved. Thanks

**Comment by armandsLa** [comment]
@ABausG will you be able to review and merge this PR?

**Comment by ABausG** [comment]
Yes sorry!! Will do it after FlutterCon

**Review by ABausG — APPROVED** [review]
LGTM - had to read a bit about async / await works on Swift. Thanks for this. currently looking into the failing android pipeline, but I should get this landed and released this weekend!

**Pull request merged**
