### PR TITLE
Feature count widgets

### PR DESCRIPTION
**Pull request by richirisu**
Hello, I added a mehtod that counts the number of widgets on the home screen.

It woks for both Android and iOS. A minor pet peeve, however, is that on iOS it is only possible to count the amount of different types and sizes (so multiple widgets of the same type and size will only count as one).

May I ask if the method parameters are corrrect, or can it be done with less?
Another thing I was also not sure about is the method description and the exception message text.

### CODE REVIEW

**Comment by Manuito83** [comment]
Working properly in Android, thanks

**Comment by ABausG** [comment]
Hey sorry for never getting back to this! Just had a first look and looks good both from a feature perspective and also from an api design perspective.

Would be up for continue working on this even though it took me over a year to get back to you on this?

What is missing in my view:
1. Adding Tests
2. Some more documentation especially regarding the limits of iOS you are talking about


Please let me know if want to pick this up again/have the time for it. Otherwise I'd be happy to take this over once I have the time

**Comment by prateekmedia** [comment]
@ABausG I have added missing tests and documentation in #237

**Comment by ABausG** [comment]
Closed in favor of #237

**Pull request closed without merging**
